# Generated by Django 4.0 on 2022-02-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
    ]
